### ISSUE TITLE
`--app` is still required even if `CPLN_APP` is provided

### ISSUE THREAD

**Issue by ahangarha** [shakacode/heroku-to-control-plane#108]
Currently, commands like `apply-template` require `--app` even if `CPLN_APP` env variable is set.

```
➜ cpl apply-template gvc rails postgres redis daily-task 
No value provided for required options '--app'
➜ cpl apply-template gvc rails postgres redis daily-task --app $CPLN_APP
...
```

**Comment by rafaelgomesxyz** [comment]
Hm, I don't see why it would do that specifically for `apply-template` and not, let's say, for `latest-image`, since they use `app_option` the exact same way (`app_option(required: true)`), and `app_option` has a default value of `ENV.fetch("CPLN_APP", nil)`. Or did you not test with other commands? And if you did, which commands did you test?

**Comment by rafaelgomesxyz** [comment]
Something that could be causing this, because I just ran into it: you might have an old version of `cpl` installed that doesn't have the functionality yet.

When I ran `cpl apply-template` I got the error, but when I ran `../heroku-to-control-plane/cpl` (which is where I have the project with the latest code) I didn't.

**Comment by ahangarha** [comment]
I usually make alias for cpl. It is possible that I missed it. I close the issue for now and reopen if I notice the issue persist even if I use cpl with latest changes.
